id: ESC50-32k
_target_: esc_50.ESC50

path: data/ESC50
features_subdir: log_mel_32k
index_column: filename
target_column: category
file_type: npy
file_handler: autrainer.datasets.utils.NumpyFileHandler

train_folds: [1, 2, 3]
dev_folds: [4]
test_folds: [5]

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.Accuracy

transform:
  type: grayscale
