id: SpectrogramDataset-32k
_target_: autrainer.datasets.BaseClassificationDataset

path: data/SpectrogramDataset # base path to the dataset
features_subdir: log_mel_32k # spectrogram preprocessed features
index_column: path # column in the CSVs containing features paths relative to features_subdir
target_column: label # column in the CSVs containing the target labels
file_type: npy # file extension of the spectrogram features
file_handler: autrainer.datasets.utils.NumpyFileHandler # file handler for the spectrogram features

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.Accuracy

transform:
  type: grayscale