# Important: should be used with inference_batch_size: 1
id: AIBO-wav
_target_: autrainer.datasets.AIBO

aibo_task: 2cl

path: data/AIBO
features_subdir: default
index_column: file
target_column: class
file_type: wav
file_handler: autrainer.datasets.utils.AudioFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.Accuracy

transform:
  type: raw