# Important: should be used with inference_batch_size: 1
id: AIBO-eGeMAPS-llds
_target_: autrainer.datasets.AIBO

aibo_task: 2cl

path: data/AIBO
features_subdir: eGeMAPSv02-llds
index_column: file
target_column: class
file_type: npy
file_handler: autrainer.datasets.utils.NumpyFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.Accuracy

transform:
  type: tabular
  base:
    - autrainer.transforms.Expand:
        size: 200
  train:
    - autrainer.transforms.RandomCrop:
        size: 200