id: DCASE2018Task3-wav
_target_: autrainer.datasets.DCASE2018Task3

dev_split: 0.1
dev_split_seed: 0

path: data/DCASE2018Task3
features_subdir: default
index_column: filename
target_column: hasbird
file_type: wav
file_handler: autrainer.datasets.utils.AudioFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics:
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.Accuracy

transform:
  type: raw