id: DCASE2016Task1-wav-stm
_target_: autrainer.datasets.DCASE2016Task1

fold: 1

path: data/DCASE2016
features_subdir: default
index_column: filename
target_column: scene_label
file_type: wav
file_handler: autrainer.datasets.utils.AudioFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.Accuracy

transform:
  type: raw
  base:
    - autrainer.transforms.StereoToMono