id: DCASE2016Task1-32k
_target_: autrainer.datasets.DCASE2016Task1

fold: 1

path: data/DCASE2016
features_subdir: log_mel_32k
index_column: filename
target_column: scene_label
file_type: npy
file_handler: autrainer.datasets.utils.NumpyFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.Accuracy

transform:
  type: grayscale