id: EmoDB-wav
_target_: autrainer.datasets.EmoDB

train_speakers: [3, 8, 9, 10, 11, 12]
dev_speakers: [13, 14]
test_speakers: [15, 16]

path: data/EmoDB
features_subdir: default
index_column: filename
target_column: emotion
file_type: wav
file_handler: autrainer.datasets.utils.AudioFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics:
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.Accuracy

transform:
  type: raw
  base:
    - autrainer.transforms.Expand:
        size: 144000 # 16khz * 9s
        axis: -1