# Important: should be used with inference_batch_size: 1
id: MSPPodcast-EmoClass-big4-wav
_target_: autrainer.datasets.MSPPodcast

path: data/MSPPodcast
index_column: FileName
target_column: EmoClass
file_type: wav
file_handler: autrainer.datasets.utils.AudioFileHandler

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics: 
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.Accuracy

categories: [A,H,N,S]

transform:
  type: raw
  base:
    - autrainer.transforms.Expand:
        size: 48000
        axis: -1
  train:
    - autrainer.transforms.RandomCrop:
        size: 48000
        axis: -1