id: ToyAudio-R
_target_: autrainer.datasets.ToyDataset

task: regression
size: 1000
num_targets: 1
feature_shape: [1, 48000]
dev_split: 0.2
test_split: 0.2

criterion: autrainer.criterions.MSELoss
metrics:
  - autrainer.metrics.PCC
  - autrainer.metrics.CCC
  - autrainer.metrics.MSE
  - autrainer.metrics.MAE
tracking_metric: autrainer.metrics.PCC

transform:
  type: raw