id: ToyImage-R
_target_: autrainer.datasets.ToyDataset

task: regression
size: 1000
num_targets: 1
feature_shape: [3, 64, 64]
dev_split: 0.2
test_split: 0.2
dtype: uint8

criterion: autrainer.criterions.MSELoss
metrics:
  - autrainer.metrics.PCC
  - autrainer.metrics.CCC
  - autrainer.metrics.MSE
  - autrainer.metrics.MAE
tracking_metric: autrainer.metrics.PCC

transform:
  type: image
  base:
    - autrainer.transforms.ScaleRange
    - autrainer.transforms.Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]