id: ToyImage-C
_target_: autrainer.datasets.ToyDataset

task: classification
size: 1000
num_targets: 10
feature_shape: [3, 64, 64]
dev_split: 0.2
test_split: 0.2
dtype: uint8

criterion: autrainer.criterions.BalancedCrossEntropyLoss
metrics:
  - autrainer.metrics.Accuracy
  - autrainer.metrics.UAR
  - autrainer.metrics.F1
tracking_metric: autrainer.metrics.Accuracy

transform:
  type: image
  base:
    - autrainer.transforms.ScaleRange
    - autrainer.transforms.Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]