file_handler:
  autrainer.datasets.utils.AudioFileHandler:
    target_sample_rate: 16000
pipeline:
  - autrainer.transforms.StereoToMono
  - autrainer.transforms.OpenSMILE:
      feature_set: ComParE_2016
      sample_rate: 16000