id: Cnn10-32k-T-online
_target_: autrainer.models.Cnn10
transfer: https://zenodo.org/records/3987831/files/Cnn10_mAP%3D0.380.pth

transform:
  type: raw
  base:
    - autrainer.transforms.Resample:
        current_sr: 48000
        target_sr: 32000
    - autrainer.transforms.PannMel:
        sample_rate: 32000
        window_size: 1024
        hop_size: 320
        mel_bins: 64
        fmin: 50
        fmax: 14000
        ref: 1.0
        amin: 1e-10
        top_db: null
