id: Cnn14-32k-T
_target_: autrainer.models.Cnn14
transfer: https://zenodo.org/records/3987831/files/Cnn14_mAP%3D0.431.pth

transform:
  type: grayscale
  base:
    - autrainer.transforms.Normalize: null