id: GoogLeNet-T
_target_: autrainer.models.TorchvisionModel
torchvision_name: googlenet
transfer: true
aux_logits: false
transform:
  type: image
  base:
    - autrainer.transforms.Resize:  
        height: 224
        width: 224