id: InceptionV3-T
_target_: autrainer.models.TorchvisionModel
torchvision_name: inception_v3
transfer: true
aux_logits: false

transform:
  type: image
  base:
    - autrainer.transforms.Resize:  
        height: 299
        width: 299
