id: MaxViT-T
_target_: autrainer.models.TorchvisionModel
torchvision_name: maxvit_t
transfer: false
transform:
  type: image
  base:
    - autrainer.transforms.Resize:  
        height: 224
        width: 224
