id: Seq-FFNN-IS10
_target_: autrainer.models.SeqFFNN
backbone_input_dim: 76
backbone_cell: LSTM
backbone_hidden_size: 32
backbone_num_layers: 2
hidden_size: 32
num_layers: 2
dropout: 0.5

transform:
  type: tabular