id: Swin-S-T
_target_: autrainer.models.TorchvisionModel
torchvision_name: swin_s
transfer: true
transform:
  type: image
  base:
    - autrainer.transforms.Resize:  
        height: 224
        width: 224