id: Swin-V2-T-T
_target_: autrainer.models.TorchvisionModel
torchvision_name: swin_v2_t
transfer: true
transform:
  type: image
  base:
    - autrainer.transforms.Resize:  
        height: 256
        width: 256
