id: ViT-B-16-T
_target_: autrainer.models.TorchvisionModel
torchvision_name: vit_b_16
transfer: true
transform:
  type: image
  base:
    - autrainer.transforms.Resize:  
        height: 224
        width: 224
