id: ViT-L-32
_target_: autrainer.models.TorchvisionModel
torchvision_name: vit_l_32
transfer: false
transform:
  type: image
  base:
    - autrainer.transforms.Resize:  
        height: 224
        width: 224
