id: w2v2-l-rob
_target_: autrainer.models.W2V2FFNN
model_name: facebook/wav2vec2-large-robust
freeze_extractor: true
hidden_size: 512
num_layers: 2
dropout: 0.5

transform:
  type: raw
  base:
    - autrainer.transforms.FeatureExtractor:
        fe_type: W2V2
        fe_transfer: facebook/wav2vec2-large-robust