id: w2v2-l-emo-T
_target_: autrainer.models.W2V2FFNN
model_name: audeering/wav2vec2-large-robust-12-ft-emotion-msp-dim
freeze_extractor: true
hidden_size: 512
num_layers: 2
dropout: 0.5
transfer: true

transform:
  type: raw
  base:
    - autrainer.transforms.FeatureExtractor:
        fe_type: W2V2
        fe_transfer: audeering/wav2vec2-large-robust-12-ft-emotion-msp-dim
