defaults:
  - _autrainer_
  - _self_

results_dir: results
experiment_id: spectrogram
iterations: 5

hydra:
  sweeper:
    params:
      +seed: 1
      +batch_size: 32
      +learning_rate: 0.001
      dataset: DCASE2016Task1-32k
      model: Cnn10-32k-T
      optimizer: Adam