defaults:
  - _autrainer_train_
  - _self_

results_dir: results
experiment_id: default
iterations: 5

hydra:
  sweeper:
    params:
      +seed: 1, 2, 3
      +batch_size: 32
      +learning_rate: 0.001
      dataset: ToyTabular-C
      model: ToyFFNN, Three-Layer-FFNN
      optimizer: Adam
    filters:
      - hydra_filter_sweeper.Exists:
          path: metrics.csv
      - hydra_filter_sweeper.Expression:
          expr: model.id == "Three-Layer-FFNN" and seed > 2
