name: CI

on: pull_request

permissions:
  contents: read

jobs:
  test:
    name: CI Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"] #TODO: "3.11", "3.12", ...
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv and set Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Sync dependencies
        run: uv sync --locked --all-extras --all-groups
      - name: Run pre-commit
        run: uv run pre-commit run --all-files
      - name: Run tests
        run: uv run pytest tests
